apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  namespace: rabbitmq
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: rabbitmq-pvc
    namespace: rabbitmq
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /nfs/data/rabbitmq-single
    server: 172.16.124.130
  volumeMode: Filesystem
