apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: rabbitmq
  labels:
    app: rabbitmq
data:
    enabled_plugins: |
      [rabbitmq_shovel,rabbitmq_shovel_management].
    rabbitmq.conf: |+
      loopback_users.guest = false # 解除guest用户限制
