apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-cluster-pv-0
  namespace: rabbitmq
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: rabbitmq-local-storage
  local:
    path: /data/rabbitmq/data-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - slave1.xincan.cn

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-cluster-pv-1
  namespace: rabbitmq
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: rabbitmq-local-storage
  local:
    path: /data/rabbitmq/data-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - slave2.xincan.cn

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-cluster-pv-2
  namespace: rabbitmq
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: rabbitmq-local-storage
  local:
    path: /data/rabbitmq/data-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - slave2.xincan.cn
