apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-cluster-secret
  namespace: rabbitmq
stringData:
  #cookie: ERLANG_COOKIE
  cookie: j83ao4fZj5x9XGAVip0f/tU5Vfw1DbN291hc7qLRR0Y=  # echo $(openssl rand -base64 32) 
  username: admin
  password: admin123
type: Opaque
