apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: mysql
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mysql-pvc
    namespace: mysql
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /nfs/data/mysql-single
    server: 172.16.124.130
  volumeMode: Filesystem
