apiVersion: v1
kind: ConfigMap
metadata:
  name: seata-server-config
  namespace: seata
data:
  registry.conf: |
    registry {
      type = "nacos"
      nacos {
        application = "seata-service"
        serverAddr = "nacos-service.nacos:8848"
        namespace = "seata-0001"
        group = "SEATA_GROUP"
        username = "nacos"
        password = "nacos"
      }
    }
    config {
      type = "nacos"
      nacos {
        serverAddr = "nacos-service.nacos:8848"
        namespace = "seata-0001"
        group = "SEATA_GROUP"
        username = "nacos"
        password = "nacos"
      }
    }
