apiVersion: v1
kind: Service
metadata:
  name: seata-service
  namespace: seata
  labels:
    app: seata
spec:
  selector:
    app: seata
  type: NodePort
  ports:
    - name: http
      port: 8091
      nodePort: 31180
      protocol: TCP
