apiVersion: v1
kind: Service
metadata:
  name: seata-service
  namespace: seata
  labels:
    app: seata
spec:
  type: NodePort
  ports:
    - port: 8091
      nodePort: 30091
      protocol: TCP
      name: http
  selector:
    app: seata
