apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-0
  namespace: mysql
  labels:
    app: mysql
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: mysql-local-storage
  local:
    path: /xincan/data/mysql-pv-0/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - slave142.sealer.hatech.com.cn
