apiVersion: v1
kind: Service
metadata:
  name: mysql-cluster
  namespace: mysql
  labels:
    app: mysql
spec:
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
  selector:
    app: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysql
  labels:
    app: mysql
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
  - name: http
    protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 30336
