apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: efk
  labels:
    xincan.kubernetes.io/company: xincan.cn
    xincan.kubernetes.io/version: 0.0.1
    xincan.kubernetes.io/type: plugins
    xincan.kubernetes.io/product: xincan
    xincan.kubernetes.io/app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      xincan.kubernetes.io/company: xincan.cn
      xincan.kubernetes.io/version: 0.0.1
      xincan.kubernetes.io/type: plugins
      xincan.kubernetes.io/product: xincan
      xincan.kubernetes.io/app: kibana
  template:
    metadata:
      name: kibana
      labels:
        xincan.kubernetes.io/company: xincan.cn
        xincan.kubernetes.io/version: 0.0.1
        xincan.kubernetes.io/type: plugins
        xincan.kubernetes.io/product: xincan
        xincan.kubernetes.io/app: kibana
    spec:
      serviceAccountName: fk-rbac
      restartPolicy: Always
      containers:
      - name: kibana
        image: base.hatech.com.cn/library/kibana:7.4.2
        imagePullPolicy: IfNotPresent
        
        ports:
        - containerPort: 5601
          protocol: TCP

        env:

        - name: I18N_LOCALE
          valueFrom:
            configMapKeyRef:
              name: kibana-config
              key: kibana.i18n.locale

        - name: SERVER_NAME
          valueFrom:
            configMapKeyRef:
              name: kibana-config
              key: kibana.server.name


        - name: SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: kibana-config
              key: kibana.server.host


        - name: ELASTICSEARCH_HOSTS
          valueFrom:
            configMapKeyRef:
              name: kibana-config
              key: kibana.elasticsearch.hosts
