apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: redis
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500M
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: redis-pvc
    namespace: redis
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /nfs/data/redis-single
    server: 172.16.124.130
  volumeMode: Filesystem
