apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: redis
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500M
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: redis-pvc
    namespace: redis
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /hatech/nfs/data/xincan/redis-single
    server: 192.168.1.80
  volumeMode: Filesystem
