apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client-storage
  namespace: study
provisioner: fuseim.pri/ifs # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
