apiVersion: v1
kind: PersistentVolume
metadata:
  name: nacos-pv
  namespace: nacos
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: nacos-pvc
    namespace: nacos
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /nfs/data/nacos-single
    server: 172.16.124.130
  volumeMode: Filesystem
