apiVersion: v1
kind: PersistentVolume
metadata:
  name: nacos-pv
  namespace: nacos
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: nacos-pvc
    namespace: nacos
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /hatech/nfs/data/xincan/nacos-single
    server: 192.168.1.80
  volumeMode: Filesystem
