apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nacos-pvc
  namespace: nacos
  labels:
    app: nacos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
