apiVersion: v1
kind: Service
metadata:
  name: nacos-service
  namespace: nacos
  labels:
    app: nacos
spec:
  selector:
    app: nacos
  type: NodePort
  ports:
  - name: client-port
    port: 8848
    targetPort: 8848
    nodePort: 31150
