apiVersion: v1
kind: Service
metadata:
  name: nacos-service
  namespace: nacos
  labels:
    app: nacos
spec:
  ports:
    - name: client-port
      port: 8848
      targetPort: 8848
  type: NodePort
  selector:
    app: nacos
