apiVersion: v1
kind: PersistentVolume
metadata:
  name: sentinel-pv
  namespace: sentinel
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: sentinel-pvc
    namespace: sentinel
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /hatech/nfs/data/xincan/sentinel-single
    server: 192.168.1.80
  volumeMode: Filesystem
