apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentinel-pvc
  namespace: sentinel
  labels:
    app: sentinel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
