apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinel-config
  namespace: sentinel
data:

  sentinel.server.host: "nacos-service.naco.svc.cluster.locals"
  sentinel.server.port: "8848"
  sentinel.dashboard.auth.username: "sentinel"
  sentinel.dashboard.auth.password: "sentinel"
