apiVersion: v1
kind: Service
metadata:
  name: sentinel-service
  namespace: sentinel
  labels:
    app: sentinel
spec:
  type: NodePort
  selector:
    app: sentinel
  ports:
  - name: client
    port: 8858
    nodePort: 31160
    protocol: TCP
  - name: api
    port: 8719
    nodePort: 31170
    protocol: TCP
