apiVersion: v1
kind: Service
metadata:
  name: mysql-cluster
  namespace: mysql
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
  selector:
    app: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  namespace: mysql
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 32060
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: mysql-0
    app: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  namespace: mysql
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 32070
  type: NodePort
  selector:
    app: mysql
