apiVersion: v1
kind: Service
metadata:
  name: mysql-cluster
  namespace: mysql
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
  selector:
    app: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  namespace: mysql
  labels:
    app: mysql
spec:
  selector:
    statefulset.kubernetes.io/pod-name: mysql-0
    app: mysql
  type: NodePort
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 31110

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-read-1
  namespace: mysql
  labels:
    app: mysql
spec:
  selector:
    statefulset.kubernetes.io/pod-name: mysql-1
    app: mysql
  type: NodePort
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 31120

---   

apiVersion: v1
kind: Service
metadata:
  name: mysql-read-2
  namespace: mysql
  labels:
    app: mysql
spec:
  selector:
    statefulset.kubernetes.io/pod-name: mysql-2
    app: mysql
  type: NodePort
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 31130
