apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cockroachdb-nfs-storage
  namespace: cockroachdb
provisioner: fuseim.pri/ifs-cockroachdb # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
