apiVersion: apps/v1
kind: Deployment
metadata:
  name: cockroachdb-nfs-provisioner
  labels:
    app: cockroachdb-nfs-provisioner
  # replace with namespace where provisioner is deployed
  namespace: cockroachdb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cockroachdb-nfs-provisioner
  template:
    metadata:
      labels:
        app: cockroachdb-nfs-provisioner
    spec:
      serviceAccountName: cockroachdb
      containers:
        - name: cockroachdb-nfs-provisioner
          image: base.hatech.com.cn/library/nfs-client-provisioner:v1.5.2
          volumeMounts:
            - name: cockroachdb-nfs-client-root
              # 该文件夹是nfs-client-provisioner运行之后容器内部固定的文件夹它会mount到/nfs/data/nginx nfs服务器nginx文件夹下
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs-cockroachdb
            - name: NFS_SERVER
              value: 192.168.1.80
            - name: NFS_PATH
              value: /hatech/nfs/data/xincan/cockroachdb
      volumes:
        - name: cockroachdb-nfs-client-root
          nfs:
            server: 192.168.1.80
            path: /hatech/nfs/data/xincan/cockroachdb
