kind: Deployment
apiVersion: apps/v1
metadata:
  name: nacos-nfs-client-provisioner
  namespace: nacos
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nacos-nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nacos-nfs-client-provisioner
    spec:
      serviceAccount: nacos-nfs-client-provisioner
      containers:
        - name: nacos-nfs-client-provisioner
          image: base.xincan.cn/library/nfs-client-provisioner:v1.5.2
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: NFS_SERVER
              value: 172.16.124.130
            - name: NFS_PATH
              value: /nfs/data/nacos-multiple
      volumes:
        - name: nfs-client-root
          nfs:
            server: 172.16.124.130
            path: /nfs/data/nacos-multiple
