apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-local-storage
  namespace: redis
  labels:
    app: redis
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
