apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-0
  namespace: redis
  labels:
    app: redis
spec:
  capacity:
    storage: 300M
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: redis-local-storage
  local:
    path: /data/redis/data-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - slave1.xincan.cn

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-1
  namespace: redis
  labels:
    app: redis
spec:
  capacity:
    storage: 300M
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: redis-local-storage
  local:
    path: /data/redis/data-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - slave1.xincan.cn


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-2
  namespace: redis
  labels:
    app: redis
spec:
  capacity:
    storage: 300M
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: redis-local-storage
  local:
    path: /data/redis/data-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - slave1.xincan.cn

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-3
  namespace: redis
  labels:
    app: redis
spec:
  capacity:
    storage: 300M
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: redis-local-storage
  local:
    path: /data/redis/data-3
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - slave2.xincan.cn

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-4
  namespace: redis
  labels:
    app: redis
spec:
  capacity:
    storage: 300M
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: redis-local-storage
  local:
    path: /data/redis/data-4
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - slave2.xincan.cn

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-5
  namespace: redis
  labels:
    app: redis
spec:
  capacity:
    storage: 300M
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: redis-local-storage
  local:
    path: /data/redis/data-5
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - slave2.xincan.cn
