apiVersion: v1  
kind: Service  
metadata:  
  name: redis-cluster
  namespace: redis
  labels:
    app: redis
spec:  
  type: ClusterIP
  ports:
  - name: client
    port: 6379
    targetPort: 6379
  - name: server
    port: 16379 
    targetPort: 16379
  selector:
    app: redis-cluster

---

apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-0
  namespace: redis
  labels:
    app: redis
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: client
    port: 6379
    targetPort: 6379
  - name: server
    port: 16379
    targetPort: 16379
  selector:
    statefulset.kubernetes.io/pod-name: redis-cluster-0
    app: redis-cluster

---

apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-1
  namespace: redis
  labels:
    app: redis
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: client
    port: 6379
    targetPort: 6379
  - name: server
    port: 16379
    targetPort: 16379
  selector:
    statefulset.kubernetes.io/pod-name: redis-cluster-0
    app: redis-cluster

---

apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-2
  namespace: redis
  labels:
    app: redis
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: client
    port: 6379
    targetPort: 6379
  - name: server
    port: 16379
    targetPort: 16379
  selector:
    statefulset.kubernetes.io/pod-name: redis-cluster-0
    app: redis-cluster
